#!/bin/bash
# Demo: Before and After ML Defense
# Shows the difference between attacks with and without ML detection

echo "=========================================="
echo "🛡️  DEMO: ANTES Y DESPUÉS DEL DEFENDER"
echo "=========================================="
echo ""
echo "Este demo muestra la diferencia entre:"
echo "  1. SIN defensa ML - el ataque pasa desapercibido"
echo "  2. CON defensa ML - el ataque es detectado y bloqueado"
echo ""

# Check if model exists
MODEL_PATH="/home/ryu/Desktop/Labo/SdnShare/models/ddos_dt_model.pkl"
if [ ! -f "$MODEL_PATH" ]; then
    echo "❌ Error: Modelo no encontrado"
    echo "   Entrena el modelo primero:"
    echo "   jupyter notebook /home/ryu/Desktop/Labo/SdnShare/notebooks/ddos_detection_dt.ipynb"
    exit 1
fi

echo "✅ Modelo encontrado"
echo ""

# Show current configuration
echo "=========================================="
echo "📋 CONFIGURACIÓN ACTUAL"
echo "=========================================="
echo ""
echo "Comando actual del controller (docker-compose.yaml):"
grep "command:" /home/ryu/Desktop/Labo/SdnShare/docker-compose.yaml | head -2
echo ""

# Instructions for the demo
echo "=========================================="
echo "🚀 INSTRUCCIONES PARA EL DEMO"
echo "=========================================="
echo ""
echo "PASO 1: Iniciar la red SIN defensa ML"
echo "---------------------------------------"
echo "1. Edita docker-compose.yaml y comenta la línea de ml_defender.py:"
echo "   # command: scripts/dc_switch_1.py scripts/ml_defender.py ..."
echo ""
echo "2. Inicia la red:"
echo "   cd /home/ryu/Desktop/Labo/SdnShare"
echo "   docker-compose up -d"
echo ""
echo "3. Ejecuta un ataque desde Mininet:"
echo "   docker exec -it sdnshare_mininet_1 mn"
echo "   mininet> py exec(open('scripts/attack_menu.py').read())"
echo "   -> Selecciona opción 1 (UDP Flood)"
echo ""
echo "4. Observa que el ataque pasa sin detección:"
echo "   docker logs sdnshare_controller_1 -f"
echo ""
echo "5. Detén la red:"
echo "   docker-compose down"
echo ""
echo "=========================================="
echo ""
echo "PASO 2: Iniciar la red CON defensa ML"
echo "---------------------------------------"
echo "1. Edita docker-compose.yaml y habilita ml_defender.py:"
echo "   command: scripts/dc_switch_1.py scripts/ml_defender.py ..."
echo ""
echo "2. Inicia la red:"
echo "   cd /home/ryu/Desktop/Labo/SdnShare"
echo "   docker-compose up -d"
echo ""
echo "3. Ejecuta el mismo ataque:"
echo "   docker exec -it sdnshare_mininet_1 mn"
echo "   mininet> py exec(open('scripts/attack_menu.py').read())"
echo "   -> Selecciona opción 1 (UDP Flood)"
echo ""
echo "4. Observa la detección automática:"
echo "   docker logs sdnshare_controller_1 -f"
echo "   Deberías ver:"
echo "   ⚠️ ATAQUE DETECTADO en switch X, puerto Y"
echo "   ❌ Contramedida aplicada: Puerto Y bloqueado"
echo ""
echo "=========================================="
echo ""
echo "📊 MÉTRICAS DEL MODELO"
echo "=========================================="
echo "  - Accuracy: ~95%"
echo "  - Recall (ataques): ~68%"
echo "  - Precision: ~98%"
echo ""
echo "El modelo puede detectar:"
echo "  ✅ UDP Flood"
echo "  ✅ TCP SYN Flood"  
echo "  ✅ ICMP Flood"
echo "  ✅ HTTP Flood"
echo ""
